:sourcesdir: ../../../../source

[[custom_db]]
==== Поддержка произвольной СУБД
--
Как описано в {main_man_url}/arbitrary_dbms.html[документации], вы можете реализовать работу с любой СУБД, поддерживаемой фреймворком EclipseLink ORM, на уровне конкретного проекта. Studio позволяет автоматически создавать файлы, необходимые для интеграции с нестандартными СУБД.

Выберите *CUBA > Advanced > Define Custom Database* в главном меню.

В открывшемся окне можно указать свойства базы данных, с которой вы хотели бы работать. На основе указанных свойств Studio сгенерирует код для поддержки выбранной СУБД как на этапе разработки, так и в готовом приложении.

* *DB type id* - идентификатор типа СУБД, который будет использован в качестве значения свойства `cuba.dbmsType`.
* *DB type name* - удобочитаемое имя БД, которое будет отображаться в Studio.

После нажатия *OK* Studio создаст классы Java в пакете `com.haulmont.cuba.core.sys.persistence` и классы Groovy в пакете `com.haulmont.studio.db.{db_id}` вашего проекта. Базовая реализация, сгенерированная в Studio, подходит для использования СУБД Microsoft SQLServer. Вы можете изменить её при необходимости.

Для начала приведите класс `com.haulmont.studio.db.{db_id}.{db_id}DbProperties` в соответствие с выбранной вами базой данных. После этого вы сможете выбирать эту СУБД в настройках проекта в Studio. Закройте проект и переоткройте его заново, чтобы в списке доступных СУБД появилась нужная.

Чтобы подключиться к новой базе данных из работающего приложения, скорректируйте классы `{db_id}DbmsFeatures` и `{db_id}DbTypeConverter` в пакете `com.haulmont.cuba.core.sys.persistence`. Класс `{db_id}SequenceSupport` используется только для генерации целочисленных идентификаторов и уникальных чисел.

Наконец, если это необходимо, модифицируйте класс `com.haulmont.studio.db.{db_id}.{db_id}DdlGenerator` для правильной генерации скриптов *init* и *update* в Studio. Пропустите этот шаг, если вы не планируете создавать DDL-скрипты для новой базы данных.

--

Init data скрипты для главного хранилища данных::
--
Если вы планируете использовать нестандартную СУБД в качестве основного хранилища данных проекта, сгенерируйте скрипты инициализации и обновления БД, чтобы Studio могла создать *init*-скрипты для всех компонентов приложения, включая сам фреймворк. Эти скрипты не включают в себя некоторые данные, необходимые для инициализации БД, поэтом добавьте вручную следующие команды в скрипт *Init data* вашего проекта (`30.create-db.sql`), актуально для версии платформы `7.2`:

[source, sql]
----
include::{sourcesdir}/features/data_model/cuba-init-data.sql[]
----
--

Добавление JDBC драйвера::
--
При генерации скриптов миграции БД для Studio необходим JDBC драйвер для используемой СУБД. Для нестандартной СУБД вам необходимо скачать требуемые файлы JDBC драйвера и вручную скопировать их в каталог `{USER_HOME}/.haulmont/studio/lib` (например `C:\Users\\{username}\.haulmont\studio\lib` для Windows).

После добавления файлов драйвера в соответствующий каталог, не забудьте проделать следующее:

* перезапустить IDE.
* остановить демон Gradle (выполнив команду `gradlew --stop` в терминале).
--

Пример интеграции с СУБД Firebird::
--
Пример встраивания сторонней СУБД (Firebird) в CUBA и Studio доступен здесь: https://github.com/cuba-labs/firebird-sample. Этот пример также можно использовать как аддон, чтобы добавить поддержку Firebird в ваш проект.
--
