:sourcesdir: ../../../../../source

[[modules]]
==== Управление модулями
--
Studio позволяет создавать, редактировать и удалять дополнительные модули проекта: *core*, *gui*, *web*, *web-toolkit*, *portal* и *front*. Для управления модулями используйте команды в меню *CUBA > Advanced > Manage Modules* или в контекстном меню *Project > Modules* дерева проекта.

В секции *Modules* дерева проекта отображаются модули, используемые в текущем проекте. При создании нового проекта в нём автоматически создаются модули *global*, *core* и *web*. Для каждого модуля Studio отображает файлы конфигурации, расположенные в этом модуле.
--
Автоматическое управление модулями::
--
Заметьте, что в некоторых случаях Studio может автоматически добавлять модули в ваш проект.

Например, Studio автоматически добавляет модуль *web-toolkit* в проект тогда, когда обнаруживает, что в проект добавлены два или более аддона, содержащих виджетсет (компоненты с клиентским Vaadin кодом). В таких случаях ваш проект должен содержать модуль *web-toolkit* для того, чтобы собирался полный виджетсет, содержащий клиентский код UI компонентов как из CUBA, так и всех подключенных аддонов.
--
