:sourcesdir: ../../../source

[[using_non_default_jdk]]
=== Using Non-Default JDK
--
Both IntelliJ IDEA and Gradle by default use Java Development Kit (JDK) defined by the `JAVA_HOME` environment variable to assemble and run Java projects. In order to use the non-default JDK in your project without touching global system settings, you need to perform several steps.

Let's consider this environment configuration:

* `JAVA_HOME` environment variable on the development machine points to the JDK 8, and for some reason you don't have the ability to change it.
* You've chosen to use JDK 11 in the project.
* You are going to use new Java 11 APIs, so your project needs to be compiled and run with JDK 11.

You need to perform the following steps:

* Add JDK 11 to the global list of IDEA SDKs if it hasn't been added yet. Go to the Main menu -> *File* -> *Project Structure*. Select *SDKs* in the left menu. Press *+* button -> choose *JDK* -> select JDK 11 installation folder. Press *OK* to save changes.

* When creating a new CUBA project, select "11" for the *Project SDK* field.

* For existing projects - open the Main Menu -> *File* -> *Project Structure* dialog and change the *Project* -> *Project SDK* value.

* Navigate to the project root folder and create `gradle.properties` file with the following text:
[source]
----
# Path to JDK 11
org.gradle.java.home = C:/Java/jdk-11.0.5.10-hotspot
----

* Modify the `build.gradle` file located in the project root folder. Add the following statements to the end of `configure([globalModule, coreModule, webModule])` block:
----
include::{sourcesdir}/getting_started/source-compat-11.txt[]
----

* Refresh the Gradle project configuration: *Gradle* tool window -> *Reimport All Gradle Projects*;

* Change JRE used by the *CUBA Application* run configuration. Open Main Menu -> *Run* -> *Edit configurations...* -> *CUBA Application* -> Change the *JVM* field value.

When these changes are performed, the project is going to be compiled and run with JDK 11, without needing to change global system settings.
--
