:sourcesdir: ../../../../../../source

[[additional_jdbc_drivers]]
===== Дополнительные JDBC драйверы
--
При генерации скриптов миграции БД Studio подключается к базе данных, и поэтому ей требуется JDBC драйвер, соответствующий используемой СУБД. Studio содержит встроенные JDBC драйверы для следующих типов СУБД:

* PostgreSQL
* HSQLDB
* Microsoft SQL Server
* MariaDB
* MySQL (через драйвер MariaDB)

Чтобы использовать следующие типы СУБД, вам нужно скачать JDBC драйверы самостоятельно и добавить их в Studio:

* Oracle
* Amazon RedShift
* MySQL (через проприетарный драйвер)

Добавление файла драйвера производится в экране настроек: главное меню -> *CUBA* -> *Settings* -> *Database Proprietary Drivers*.

При интеграции с <<custom_db,нестандартной СУБД>> вам нужно скопировать файлы драйвера вручную в каталог `{USER_HOME}/.haulmont/studio/lib` (например `C:\Users\\{username}\.haulmont\studio\lib` для Windows). В этот же каталог можно положить дополнительные файлы JDBC драйверов для поддерживаемых баз данных, необходимые для корректного подключения Studio к серверу БД.

После ручного копирования файлов JDBC драйвера не забудьте выполнить следующее:

* перезапустить IDE.
* остановить демон Gradle (выполнив команду `gradlew --stop` в терминале).

--