:sourcesdir: ../../../source

[[create_project]]
=== Создание нового проекта

С помощью CUBA Studio легко создавать приложения на платформе с нуля. Запустите мастер *New Project* и выполняйте шаги, описанные ниже:

. В окне *Welcome to CUBA Studio* выберите *Create New Project*, или используйте главное меню -> *File* -> *New* -> *Project*.

. Выберите *CUBA Project*.

. Введите *Project namespace* – название пространства имен, которое будет использоваться как префикс имен сущностей и таблиц базы данных. Пространство имен может состоять только из латинских букв и цифр и должно быть как можно короче. *Тщательно продумайте название на данном этапе*, так как в дальнейшем изменить его будет достаточно сложно.

. Измените *Root package*, если необходимо. Это корневой (или основной) пакет Java-классов проекта. Может быть скорректирован позже, однако ранее сгенерированные классы перемещены не будут.

. Измените *Module prefix*, если необходимо. Это значение служит префиксом названий модулей CUBA проекта. Префикс модулей возможно изменить позже.

. В поле *Project SDK* выберите JDK, соответствующий переменной окружения `JAVA_HOME`, установленной в вашей операционной системе. Если вы видите значение `<No SDK>`, то нажмите *New* и выберите каталог установки нужного JDK, например `++C:\Java\jdk8u202-b08++` на Windows или `/Library/Java/JavaVirtualMachines/jdk8u202-b08/Contents/Home` на macOS.

. Вы можете принять настройки доступа к репозиториям платформы по умолчанию или {main_man_url}/access_to_repo.html[изменить] их для конкретного проекта.

. Выберите *Platform version* – используемую в проекте версию платформы CUBA. Если у вас нет особых требований, выбирайте последнюю релизную версию.

. Для целей бета-тестирования или раннего опробования новых возможностей платформы CUBA вам может потребоваться использовать одну из нестабильных версий платформы, тех что заканчиваются суффиксами `BETA` или `SNAPSHOT`. Чтобы увидеть их в списке выбора *Platform version*, включите флажок *Show unstable versions*. Учтите также, что `SNAPSHOT`-версии публикуются только в репозиторий артефактов `repo.cuba-platform.com`.

. Выберите значение в выпадающем списке *Languages support*, чтобы сменить набор языков программирования, используемых в проекте, или оставьте рекомендуемое значение *Java*.

. Используйте поле *Available locales*, чтобы открыть диалог редактирования *Locales* и поменять набор локалей, используемых в проекте. Вы сможете изменить их позже, если потребуется.

. Нажмите *Next*.

. На втором шаге мастера вы можете установить свойства главного хранилища данных, например выбрать локальную базу данных PostgreSQL для нового проекта. Эти свойства можно изменить позже.

. Нажмите *Next*.

. Измените имя нового проекта в поле *Project name*, если необходимо. Имя должно содержать только латинские буквы, цифры и знак подчеркивания.

. *Project location* – это путь к каталогу нового проекта. Путь можно изменить, введя адрес каталога вручную или нажав на кнопку с многоточием рядом с полем.

. Нажмите *Finish*. В указанном каталоге будет создан пустой проект, и в главном окне Studio начнётся сборка проекта по скриптам Gradle и индексирование файлов проекта.

. После окончания процессов синхронизации и индексации вы увидите дерево проекта CUBA в боковой панели *Project*.

. Откройте боковую панель *Gradle*, которая по умолчанию находится справа. Щелкните по значку "гаечный ключ" (*Gradle Settings*) и выберите `Use JAVA_HOME` в поле *Gradle JVM*. Если вы не видите такого пункта в выпадающем списке, убедитесь, что вы правильно настроили окружение согласно инструкции в разделе {main_man_url}/setup.html[Установка и настройка] руководства по разработке приложений. Нажмите *OK*.

. Теперь можно начинать работу с проектом.