:sourcesdir: ../../../source

[[using_non_default_jdk]]
=== Использование неосновной JDK
--
Как IntelliJ IDEA, так и Gradle по умолчанию используют Java Development Kit (JDK), определяемую переменной `JAVA_HOME`, для сборки и запуска Java проектов. Чтобы использовать другую JDK в вашем проекте, не меняя глобальные настройки, вам необходимо проделать некоторые действия.

Рассмотрим следующую конфигурацию рабочей среды:

* Переменная среды `JAVA_HOME` на рабочей машине указывает на JDK 8, и по каким-то причинам вы не можете поменять её.
* Вы решили использовать JDK 11 в проекте.
* Вы будете использовать новые API, появившиеся в Java 11, поэтому ваш проект должен и компилироваться и запускаться под JDK 11.

Вам нужно проделать следующие шаги:

* Добавить JDK 11 в глобальный список SDK в IDEA, если она еще не добавлена. Откройте диалог через главное меню  -> *File* -> *Project Structure*. Выберите *SDKs* в левом меню. Нажмите кнопку *+* -> выберите *JDK* -> укажите каталог, куда установлена JDK 11. Нажмите *OK*, чтобы сохранить изменения.

* При создании нового проекта - выберите "11" в поле *Project SDK*.

* Для уже существующих проектов - откройте диалог через главное меню -> *File* -> *Project Structure* и измените значение поля *Project* -> *Project SDK*.

* Перейдите в корневой каталог проекта и создайте там файл `gradle.properties` со следующим содержимым:
[source]
----
# Путь к JDK 11
org.gradle.java.home = C:/Java/jdk-11.0.5.10-hotspot
----

* Подредактируйте файл `build.gradle`, расположенный в корневом каталоге проекта. Добавьте следующие выражения в конец блока `configure([globalModule, coreModule, webModule])`:
----
include::{sourcesdir}/getting_started/source-compat-11.txt[]
----

* Обновите конфигурацию Gradle проекта: панель инструментов *Gradle* -> *Reimport All Gradle Projects*;

* Измените JRE, используемую конфигурацией запуска *CUBA Application*. Главное меню -> *Run* -> *Edit configurations...* -> *CUBA Application* -> Измените значение поля *JVM*.

После выполнения этих действий проект будет компилироваться и запускаться под JDK 11, без необходимости менять глобальные системные настройки.
--
