:sourcesdir: ../../../source

[[upgrade_project]]
=== Обновление проекта

В этом разделе описан процесс обновления проекта до более новой версии платформы.

[TIP]
====
Мы рекомендуем настроить контроль версий для проекта и всегда делать commit планируемых изменений до изменения версии платформы. Это даст вам возможность видеть изменения и откатить их на предыдущую версию в случае, если обновление по каким-либо причинам завершится неудачей.
====

* Откройте проект, следуя инструкции в <<open_project,предыдущем разделе>>.

* Выберите *CUBA > Project Properties* в основном меню либо дважды нажмите на *Project > Properties* в дереве проекта CUBA.

* В открывшемся окне *CUBA Project Properties* выберите желаемую версию платформы в поле *Platform version*.

* Для целей бета-тестирования или раннего опробования новых возможностей платформы CUBA вам может потребоваться использовать одну из нестабильных версий платформы, тех что заканчиваются суффиксами `BETA` или `SNAPSHOT`. Чтобы увидеть их в списке выбора *Platform version*, включите флажок *Show unstable versions*.
+
[TIP]
====
SNAPSHOT-версии доступны только, если вы используете репозиторий артефактов repo.cuba-platform.com.
====
+
[WARNING]
====
Нестабильные (BETA и SNAPSHOT) версии платформы категорически не рекомендуется использовать в промышленной эксплуатации.
====

* Нажмите *OK*, затем подтвердите изменения.

* Если вы обновляетесь до нового feature release (к примеру, с 6.10.X до 7.0.X или с 7.0.Y до 7.1.Y), появится диалоговое окно *Migration Required*. В этом окне содержится информация об этапах миграции, которые Studio выполнит автоматически. Ознакомьтесь с этой информацией и нажмите *Migrate*.

* Studio выполнит автоматическую миграцию (при необходимости) и выполнит задачи Gradle `clean` и `undeploy`.

* Если вы обновляетесь до нового feature release, просмотрите раздел _Breaking Changes_ в {rel_notes_url}[Release Notes] и при необходимости внесите соответствующие изменения в ваш проект.

* Если к вашему проекту подключены *CUBA аддоны*, вам может потребоваться обновить их до соответствующих версий, совместимых с новой версией платформы CUBA:
** Откройте дерево проекта CUBA -> *Project* -> *Add-ons*.
** Перейдите на вкладку *Updates*.
** Выберите все аддоны, для которых предлагается обновление.
** Нажмите *Apply & Close*.
** Подождите, пока обновленные зависимости скачаются и проиндексируются.

* Попробуйте собрать проект, выполнив команду *CUBA > Build Tasks > Assemble*. Просмотрите журнал вывода и поправьте код, если в логах есть сообщения об ошибках компиляции.

* Выполните команду *CUBA > Update Database*, чтобы применить возможные изменения в системных таблицах платформы к базе данных вашего проекта.