:sourcesdir: ../../source

[[release_notes]]
== Release Notes

Version 9::
+
--
. BREAKING CHANGE: Studio now uses HSQL version 2.4.1. When you open a project using HSQL database, Studio prompts you to update the version of HSQL in the project's `build.gradle`. If you accept, the project will correctly work with the Studio v.9+. However, be aware of the following issues:
.. The application will not start if the project with the new HSQL driver is opened in a previous Studio version containing the older HSQL server;
.. In the projects with HSQL based on CUBA version before 7.1, Scheduled Tasks do not work because their table has a column named `PERIOD` which is a reserved word in HSQL 2.4.1. The column is renamed in CUBA 7.1.

. Hot deploy mechanism now deploys all dependent classes together with the changed one, which eliminates `ClassCastException` on opening modified screens.

. When selecting MySQL or Oracle database, Studio shows a dialog where you can click a link for downloading the JDBC driver from the vendor website and then upload it from the local file system to the correct locations in the project and Studio itself. After uploading a driver, restart Studio.
+
The drivers can be removed from Studio using the *CUBA > Database Proprietary Drivers* settings page.

. `DataGrid` and `TreeDataGrid` are available for browser and master-detail screen templates in the *Table type* field of the *Create CUBA Screen* wizard.

. *Extend an existing screen* and *Entity fragment* templates have been added to the *Create CUBA Screen* wizard.

. Undo/Redo actions now work correctly in the screen visual designer.

. Implemented auto-complete for data loader query in the screen designer.

. Screen designer now has a button in the canvas top right corner to switch to the screen controller.

. Warnings in screen XML when `invoke` and `datasource` attributes are used in screens based on new API.

. If you have added Groovy support in the *Project Properties* window, you can select Groovy in the *Advanced > Controller language* field of the *Create CUBA Screen* wizard.

. Services written in Groovy are shown in CUBA project tree.

. Notification about new platform versions on project opening.

. Refined gutter icons in source code editor.

. Entity attribute type can now be freely changed in the entity designer with or without refactoring.

. Enumeration designer has been implemented.

. View designer has been rewritten with native IntelliJ UI.

. Data model generator now contains screen templates based on the new API.

. All Resolved Issues:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%209%7D%20State:%20Fixed,Verified[Studio 9.0 Resolved Issues\]]
--

Version 8::
+
--
. Opening of a project for the first time is now performed through the import wizard. See <<open_project>> for details.

. The project model is now stored in a file inside the `.idea` folder, so the Gradle synchronization is not started each time the project is opened.

. The *Run/Debug Configuration* editor now allows you to select a JDK to be used for running the application server. See *JVM* field on the *Configuration* tab. The value of `JAVA_HOME` environment variable is used by default.

. Views can be renamed by the standard *Refactor > Rename* action. This action can be invoked on the view element in the CUBA project tree, on the `name` attribute of the view XML definition in the `views.xml` file, and on any reference to this view in the screen XML descriptors.

. A view editor can be invoked from the *view* field of a data container in the screen designer.

. Implemented auto-complete and usage reference for `screen` attribute of the `<fragment>` XML element in screen descriptors.

. Implemented localized message editor for menu captions. Click *Generic UI > Web Menu* in the CUBA project tree, switch to the *Structure* tab, select a menu item and click *edit* in the *Caption* field.

. Implemented warning for enum values without localized captions. If you see the warning, use the *Create message in the message bundle* quick fix to create a default caption.

. Implemented auto-complete for the names of the application properties declared in configuration interfaces. Press Ctrl+Space when defining a property in `app.properties` or `web-app.properties` files.

. All Resolved Issues:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.2.*[Studio 8.2 Resolved Issues\]]

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.0.*%20Fixed%20in%20builds:%208.1.*[Studio 8.0-8.1 Resolved Issues\]]
--

Version 7::
+
--
. If your project is based on CUBA 6.10 and uses BPM, Charts, Full-Text Search or Reports premium add-ons, you should set the premium repository access credentials in `~/.gradle/gradle.properties` as described in the {main_man_url}/access_to_repo.html#access_to_premium_repo[Developer's Manual]. Studio does not pass the credentials to Gradle.

. All Resolved Issues:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%207.3.*%20Fixed%20in%20builds:%207.4.*[Studio 7.3-7.4 Resolved Issues\]]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.2%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.2 Resolved Issues]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.0%20Fix%20versions:%207.1%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.0-7.1 Resolved Issues]
--

:sectnums:
