:sourcesdir: ../../source

[[preface]]
== Введение
--
Данное руководство содержит справочную информацию о среде разработки CUBA Studio и её возможностях, помогающих ускорить разработку приложений на платформе.

CUBA Studio основана на платформе https://www.jetbrains.com/opensource/idea/[IntelliJ Platform] с открытым исходным кодом и дополняет её функциональность следующими возможностями, специфичными для платформы CUBA:

* Автоматическая генерация скриптов сборки Gradle.

* Генерация модели данных, схемы БД и CRUD UI.

* Визуальный WYSIWYG-дизайнер компоновки экрана.

* Удобные приёмы и функции интерфейса, которые упрощают и ускоряют процесс кодирования: действия (actions), подсказки (intentions), проверки (inspections), внутренние ссылки (references).

* Простые средства для интернационализации приложений.

* Создание модели данных и экранов UI поверх существующей (legacy) базы данных.

* Hot (re)deploy - мгновенное отображение сделанных в проекте изменений в работающем приложении без необходимости перезапускать сервер.

* Удобная миграция на более новые версии платформы и дополнений (Add-ons).

IntelliJ Platform предоставляет мощный фундамент для среды разработки CUBA Studio. Она содержит множество функций, ускоряющих производительность CUBA-разработчика, таких как удобный пользовательский интерфейс, контекстнозависимое автодополнение, безопасные рефакторинги кода, фоновые проверки корректности, встроенные средства контроля версий и интеграция с Gradle. Если вы не использовали IntelliJ IDEA раньше, то мы рекомендуем вам посетить секцию https://www.jetbrains.com/idea/documentation/[Learn & Support section] веб-сайта IntelliJ IDEA, чтобы ознакомиться с её основными возможностями и особенностями.
--
