:sourcesdir: ../../source

[[release_notes]]
== Release Notes

Версия 9::
+
--
. BREAKING CHANGE: Studio теперь включает HSQL версии 2.4.1. При первом открытии проекта, использующего базу данных HSQL, Studio предлагает обновить версию HSQL в файле `build.gradle` проекта. После обновления, проект будет корректно работать в Studio версии 9+. Однако, имейте в виду следующие возможные проблемы:
.. Приложение не сможет стартовать, если проект с новым драйвером HSQL будет открыт в предыдущей версии Studio, содержащей старый сервер HSQL;
.. В проектах с HSQL на базе CUBA версии ниже 7.1, Scheduled Tasks не работают, так как их таблица содержит колонку с именем `PERIOD`, которое является зарезервированным словом в HSQL 2.4.1. Колонка переименована в CUBA 7.1.

. Механизм Hot deploy теперь деплоит все зависимые классы вместе с измененным, что исключает `ClassCastException` при открытии измененных экранов.

. При выборе базы данных MySQL или Oracle, Studio отображает диалог, из которого можно перейти по ссылке на сайт поставщика для загрузки драйвера, а затем загрузить его из локальной файловой системы в нужный каталог проекта в саму Studio. После загрузки драйвера перезапустите Studio.
+
Драйверы могут быть удалены из Studio с помощью страницы настроек *CUBA > Database Proprietary Drivers*.

. Для шаблонов browser и master-detail мастера *Create CUBA Screen* можно выбрать компоненты `DataGrid` или `TreeDataGrid`.

. В мастер *Create CUBA Screen* добавлены шаблоны *Extend an existing screen* и *Entity fragment*.

. Действия Undo/Redo теперь корректно работают в дизайнере экранов.

. Реализовано автодополнение для запросов загрузчиков данных в дизайнере экранов.

. В дизайнер экранов добавлена кнопка для быстрого переключения на контроллер, см. верхний правый угол холста.

. Добавлены предупреждения об использовании атрибутов `invoke` и `datasource` в экранах основанных на новом API.

. Если поддержка Groovy выбрана в окне *Project Properties*, Groovy может быть выбран в поле *Advanced > Controller language* мастера *Create CUBA Screen*.

. Сервисы, написанные на Groovy, отображаются в дереве проекта CUBA.

. Добавлено оповещение о доступности новых версий платформы при открытии проекта.

. Улучшены gutter icons в редакторе исходного кода.

. Тип атрибута сущности может быть произвольно изменен в дизайнере сущности с запуском рефакторинга или без него.

. Реализован дизайнер Enumeration.

. Дизайнер представлений переписан на нативный IntelliJ UI.

. Генератор модели данных теперь содержит шаблоны экранов с новым API.

. Все завершенные задачи:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%209%7D%20State:%20Fixed,Verified[Studio 9.0 Resolved Issues\]]
--

Версия 8::
+
--
. Первое открытие проекта теперь выполняется с помощью мастера импорта проектов. См. <<open_project>> для подробной информации.

. Модель проекта теперь сохраняется в файле внутри каталога `.idea` проекта, поэтому синхронизация Gradle не запускается каждый раз при открытии проекта.

. Редактор *Run/Debug Configuration* теперь позволяет выбрать JDK, который должен использоваться для запуска сервера приложения: см. поле *JVM* на вкладке *Configuration*. По умолчанию используется значение переменной окружения `JAVA_HOME`.

. Представления (views) можно переименовывать с помощью стандартного действия *Refactor > Rename*. Это действие можно вызвать в дереве проекта CUBA, на атрибуте `name` XML-элемента `view` в файле `views.xml`, а также на любой ссылке на представление в XML-дескрипторах экранов.

. Редактор представления можно вызвать из поля *view* контейнера данных в дизайнере экрана.

. Реализовано автодополнение и поиск ссылок для атрибута `screen` XML-элемента `<fragment>` в дескрипторах экранов.

. Реализован редактор локализованных сообщений для заголовков меню. Щелкните *Generic UI > Web Menu* в дереве проекта CUBA, переключитесь на вкладку *Structure*, выберите пункт меню и нажмите *edit* в поле *Caption*.

. Реализовано предупреждение для значений перечислений, не имеющих локализованных заголовков. Если вы увидели предупреждение, используйте quick fix *Create message in the message bundle* для создания заголовка по умолчанию.

. Реализовано автодополнение для имен свойств приложения, декларированных в конфигурационных интерфейсах. Нажмите Ctrl+Space при задании свойства в файлах `app.properties` или `web-app.properties`.

. Все завершенные задачи:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.2.*[Studio 8.2 Resolved Issues\]]

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.0.*%20Fixed%20in%20builds:%208.1.*[Studio 8.0-8.1 Resolved Issues\]]
--

Версия 7::
+
--
. Если ваш проект базируется на CUBA 6.10 и использует премиум-дополнения BPM, Charts, Full-Text Search или Reports, необходимо установить имя и пароль доступа к репозиторию в файле `~/.gradle/gradle.properties`, как описано в {main_man_url}/access_to_repo.html#access_to_premium_repo[Руководстве по разработке приложений]. Studio не передает имя и пароль доступа к репозиторию в Gradle.

. Все завершенные задачи:

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%207.3.*%20Fixed%20in%20builds:%207.4.*[Studio 7.3-7.4 Resolved Issues\]]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.2%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.2 Resolved Issues]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.0%20Fix%20versions:%207.1%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.0-7.1 Resolved Issues]
--

:sectnums:
