:sourcesdir: ../../source

[[update]]
== Обновление

[[update_ide]]
Обновление IDE::
+
--
Вы можете просто загрузить новую версию Studio IDE с {cuba-download-site}[веб-сайта] и установить ее поверх имеющейся версии. Все настройки будут сохранены.

Вместо загрузки и инсталляции IDE целиком, можно настроить автоматическое обновление плагина CUBA из репозитория плагинов:

. Откройте диалог *Plugins*.

. Переключитесь на вкладку *Updates*.

. Если есть доступные обновления, вы увидите их в списке. Нажмите *Update* для плагина CUBA, и  IDE загрузит новую версию.

. После завершения процесса загрузки необходимо перезапустить IDE для применения новой версии плагина.
--

[[update_plugin]]
Обновление плагина в IntelliJ IDEA::
+
--
. Выберите *Help > Check for Update* на Windows и Linux, или *IntelliJ IDEA > Check for Updates* на macOS.

. Если есть доступные обновления, вы увидите их в списке. Выберите плагин CUBA и нажмите *Update*. IDE загрузит новую версию.

. После завершения процесса загрузки необходимо перезапустить IDE для применения новой версии плагина.
--